### ISSUE TITLE
Purposed improvement roadmap

### ISSUE THREAD

**Issue by nalzok** [karlkumbier/iRF2.0#8]
### Top priority

- [X] Read papers and try to understand the algorithms.
- [X] Familiar myself with the existent code base.
- [ ] Add more comprehensive tests (current ones don't even pass, it seems). This is important because we cannot refactor the code with confidence if there are no tests to make sure the changes we have made won't break things. Tests will also be used in profiling.
  - [x] Add tests for `RIT`
  - [ ] Add tests for `combine`
  - [X] Add tests for `gRIT`
  - [ ] Add tests for `grow`
  - [X] Add tests for `iRF`
  - [ ] Add tests for `importance`
  - [x] Add tests for `interactPredict`
  - [x] Add tests for `margin`
  - [ ] Add tests for `na.roughfix`
  - [ ] Add tests for `outlier`
  - [ ] Add tests for `plotInt`
  - [ ] Add tests for `randomForest`
  - [X] Add tests for `readForest`
  - [ ] Add tests for `rfImpute`
  - [X] Add tests for `stabilityScore`
  - [ ] Add tests for `treesize`
  - [ ] Add tests for `tuneRF`
  - [ ] Add tests for `varImpPlot`
  - [ ] Add tests for `varUsed`
- [x] Profile and optimize the bottleneck part, maybe rewrite it with `RCpp` if it's worth the effort. However, now it seems that training the random forest is the bottleneck even for moderately sized datasets, in which case not much improvement can be made.
  - [X] Profile with a real-world use case and locate the bottlenecks.
  - [x] If necessary, learn C++ and RCpp. I haven't used C++ in a serious project yet, but I know C, Java, and Python, so hopefully, it won't take a long time to make me productive.
  - [x] Remove unnecessary parts. ~~For example, `getParent` seems like something we can avoid computing.~~ (Nope, it's already part of the interface.)

### Medium priority

- [ ] Simplify API while maintaining back-compatibility. This is especially helpful for those who don't have a strong statistical background.
- [ ] Better documentation, examples, and vignettes, which are also for beginner-friendliness.
- [x] The algorithm has evolved a little since the paper was published, so we'd better record these changes in detail as well.
- [ ] Fix typos in documentation, etc.

### Low priority

- [x] If possible, replace `if (class(xxx) == 'ranger')` with S3 methods for more consistent handling of `ranger` and `randomForest`.
- [x] Reinventing wheel should also be avoided, for example `ranger::treeInfo` can be used to implement `iRF::getTree.ranger`. Likewise for `iRF::getTree.randomForest` there is already `randomForest::getTree` at our disposal.
- [ ] Launch a marketing campaign and introduce people to use `iRF`. More exposure means more suggestions and contributions, I suppose.
- [ ] Coverage and continuous integration.
